const XLSX = require('xlsx');
const fs = require('fs-extra');

const workbook = XLSX.readFile('./cypress/fixtures/Implementation_SRF.xlsx');
const sheet = workbook.Sheets[workbook.SheetNames[0]];
const rows = XLSX.utils.sheet_to_json(sheet);

const data = {};

rows.forEach(row => {

  const contractType = row['Contract Type'];   // 👈 IMPORTANT CHANGE

  if (!contractType) return;

  if (!data[contractType]) {
    data[contractType] = [];
  }

  data[contractType].push({
    name: row['Field Name'],
    type: row['Field Type']
  });
});

fs.writeJsonSync('./cypress/fixtures/categories.json', data, { spaces: 2 });

console.log("✔ JSON generated by Contract Type");